Repository nkucs/admin-frontend, pull requests merged in 2019-05, with the labels that each got.

#34 fix: change the components of first-class side menu to PageView (#33)
  src/config/router.config.js
  src/views/permission/RoleDistribution.vue
  src/views/permission/RoleModification.vue
Labels: bug

#42 chenfanglei/add the StaffDetail page ui
  src/views/staff/StaffDetail.vue
Labels: enhancement

#44 chenfanglei/add the StaffCreation page ui
  src/views/staff/StaffCreation.vue
Labels: enhancement

#43 chenfanglei/add the StaffModification page ui
  src/views/staff/StaffModification.vue
Labels: enhancement

#47 fix: fix lint warnings in staffcreation (#46)
  src/views/staff/StaffCreation.vue
Labels: bug

#51 Tanglei
  package-lock.json
  src/views/student/StudentChange.vue
  src/views/student/StudentCreation.vue
Labels: enhancement

#57 Dingquan/finish router config
  src/config/router.config.js
  src/views/student/StudentModification.vue
Labels: bug, enhancement

#62 tanglei
  src/views/student/StudentCreation.vue
  src/views/student/StudentModification.vue
Labels: enhancement
